# 液态神经网络电力负荷预测模型配置

data:
  # 序列长度（历史时间步数）
  sequence_length: 24
  
  # 预测步长（未来时间步数）
  forecast_horizon: 1
  
  # 时间特征
  time_features:
    - year
    - month
    - day
    - hour
    - dayofweek
    - weekend
    - quarter
  
  # 滞后特征
  lag_features: [1, 2, 3, 24, 168]
  
  # 滚动窗口特征
  rolling_windows: [3, 6, 12, 24]

model:
  # 模型类型: liquid_ode 或 liquid_lstm
  type: liquid_ode
  
  # 隐藏层大小
  hidden_size: 64
  
  # 学习率
  learning_rate: 0.001
  
  # 训练轮数
  epochs: 100
  
  # 批次大小
  batch_size: 32
  
  # ODE求解方法 (适用于liquid_ode)
  ode_method: dopri5

training:
  # 验证集比例
  validation_split: 0.2
  
  # 是否打乱数据
  shuffle: True

evaluation:
  # 评估指标
  metrics:
    - MSE
    - RMSE
    - MAE
    - MAPE
    - R2